// Auto-generated by fetch_logos.py
package com.ritesh.cashiro.presentation.common.icons

import com.ritesh.cashiro.R

object BrandIcons {
    private val brandMappings = mapOf(
        "1mg" to R.drawable.ic_brand_1mg,
        "5paisa" to R.drawable.ic_brand_5paisa,
        "99acres" to R.drawable.ic_brand_99acres,
        "abhibus" to R.drawable.ic_brand_abhibus,
        "acko" to R.drawable.ic_brand_acko,
        "adani electricity" to R.drawable.ic_brand_adani_electricity,
        "air india" to R.drawable.ic_brand_air_india,
        "airtel" to R.drawable.ic_brand_airtel,
        "ajio" to R.drawable.ic_brand_ajio,
        "amazon" to R.drawable.ic_brand_amazon,
        "amazon pay" to R.drawable.ic_brand_amazon_pay,
        "amazon prime" to R.drawable.ic_brand_amazon_prime,
        "angel one" to R.drawable.ic_brand_angel_one,
        "anytime fitness" to R.drawable.ic_brand_anytime_fitness,
        "apollo pharmacy" to R.drawable.ic_brand_apollo_pharmacy,
        "apple music" to R.drawable.ic_brand_apple_music,
        "axis bank" to R.drawable.ic_brand_axis_bank,
        "bajaj allianz" to R.drawable.ic_brand_bajaj_allianz,
        "bandhan bank" to R.drawable.ic_brand_bandhan_bank,
        "bank of baroda" to R.drawable.ic_brand_bank_of_baroda,
        "barbeque nation" to R.drawable.ic_brand_barbeque_nation,
        "bhim" to R.drawable.ic_brand_bhim,
        "bigbasket" to R.drawable.ic_brand_bigbasket,
        "blinkit" to R.drawable.ic_brand_blinkit,
        "blu smart" to R.drawable.ic_brand_blu_smart,
        "bookmyshow" to R.drawable.ic_brand_bookmyshow,
        "bounce" to R.drawable.ic_brand_bounce,
        "bses" to R.drawable.ic_brand_bses,
        "bsnl" to R.drawable.ic_brand_bsnl,
        "burger king" to R.drawable.ic_brand_burger_king,
        "byjus" to R.drawable.ic_brand_byjus,
        "cafe coffee day" to R.drawable.ic_brand_cafe_coffee_day,
        "canara bank" to R.drawable.ic_brand_canara_bank,
        "cinepolis" to R.drawable.ic_brand_cinepolis,
        "cleartrip" to R.drawable.ic_brand_cleartrip,
        "coin" to R.drawable.ic_brand_coin,
        "coursera" to R.drawable.ic_brand_coursera,
        "cred" to R.drawable.ic_brand_cred,
        "cultfit" to R.drawable.ic_brand_cultfit,
        "curefit" to R.drawable.ic_brand_curefit,
        "dish tv" to R.drawable.ic_brand_dish_tv,
        "department of post" to R.drawable.ic_brand_dop,
        "dop" to R.drawable.ic_brand_dop,
        "dmart" to R.drawable.ic_brand_dmart,
        "dominos" to R.drawable.ic_brand_dominos,
        "dream11" to R.drawable.ic_brand_dream11,
        "dunzo" to R.drawable.ic_brand_dunzo,
        "economic times" to R.drawable.ic_brand_economic_times,
        "eros now" to R.drawable.ic_brand_eros_now,
        "etmoney" to R.drawable.ic_brand_etmoney,
        "federal bank" to R.drawable.ic_brand_federal_bank,
        "firstcry" to R.drawable.ic_brand_firstcry,
        "fitternity" to R.drawable.ic_brand_fitternity,
        "flipkart" to R.drawable.ic_brand_flipkart,
        "freecharge" to R.drawable.ic_brand_freecharge,
        "gaana" to R.drawable.ic_brand_gaana,
        "goibibo" to R.drawable.ic_brand_goibibo,
        "golds gym" to R.drawable.ic_brand_golds_gym,
        "great learning" to R.drawable.ic_brand_great_learning,
        "grofers" to R.drawable.ic_brand_grofers,
        "groww" to R.drawable.ic_brand_groww,
        "haldirams" to R.drawable.ic_brand_haldirams,
        "hathway" to R.drawable.ic_brand_hathway,
        "hdfc bank" to R.drawable.ic_brand_hdfc_bank,
        "hdfc life" to R.drawable.ic_brand_hdfc_life,
        "healthifyme" to R.drawable.ic_brand_healthifyme,
        "healthkart" to R.drawable.ic_brand_healthkart,
        "hindustan times" to R.drawable.ic_brand_hindustan_times,
        "housejoy" to R.drawable.ic_brand_housejoy,
        "housingcom" to R.drawable.ic_brand_housingcom,
        "icici bank" to R.drawable.ic_brand_icici_bank,
        "icici prudential" to R.drawable.ic_brand_icici_prudential,
        "idfc first bank" to R.drawable.ic_brand_idfc_first_bank,
        "ind money" to R.drawable.ic_brand_ind_money,
        "indian express" to R.drawable.ic_brand_indian_express,
        "indigo" to R.drawable.ic_brand_indigo,
        "indusind bank" to R.drawable.ic_brand_indusind_bank,
        "inox" to R.drawable.ic_brand_inox,
        "irctc" to R.drawable.ic_brand_irctc,
        "ixigo" to R.drawable.ic_brand_ixigo,
        "jio" to R.drawable.ic_brand_jio,
        "jiomart" to R.drawable.ic_brand_jiomart,
        "jiosaavn" to R.drawable.ic_brand_jiosaavn,
        "kfc" to R.drawable.ic_brand_kfc,
        "kotak mahindra bank" to R.drawable.ic_brand_kotak_mahindra_bank,
        "kuvera" to R.drawable.ic_brand_kuvera,
        "lazypay" to R.drawable.ic_brand_lazypay,
        "lic" to R.drawable.ic_brand_lic,
        "lybrate" to R.drawable.ic_brand_lybrate,
        "magicbricks" to R.drawable.ic_brand_magicbricks,
        "makemytrip" to R.drawable.ic_brand_makemytrip,
        "max life" to R.drawable.ic_brand_max_life,
        "mcdonalds" to R.drawable.ic_brand_mcdonalds,
        "medlife" to R.drawable.ic_brand_medlife,
        "meesho" to R.drawable.ic_brand_meesho,
        "microsoft teams" to R.drawable.ic_brand_microsoft_teams,
        "mobikwik" to R.drawable.ic_brand_mobikwik,
        "mpl" to R.drawable.ic_brand_mpl,
        "mtnl" to R.drawable.ic_brand_mtnl,
        "mx player" to R.drawable.ic_brand_mx_player,
        "myntra" to R.drawable.ic_brand_myntra,
        "netflix" to R.drawable.ic_brand_netflix,
        "netmeds" to R.drawable.ic_brand_netmeds,
        "nobroker" to R.drawable.ic_brand_nobroker,
        "nykaa" to R.drawable.ic_brand_nykaa,
        "ola" to R.drawable.ic_brand_ola,
        "ola electric" to R.drawable.ic_brand_ola_electric,
        "paytm" to R.drawable.ic_brand_paytm,
        "paytm first games" to R.drawable.ic_brand_paytm_first_games,
        "paytm insider" to R.drawable.ic_brand_paytm_insider,
        "paytm money" to R.drawable.ic_brand_paytm_money,
        "pepperfry" to R.drawable.ic_brand_pepperfry,
        "pharmeasy" to R.drawable.ic_brand_pharmeasy,
        "phonepe" to R.drawable.ic_brand_phonepe,
        "prime commercial bank" to R.drawable.ic_brand_prime_commercial_bank,
        "pizza hut" to R.drawable.ic_brand_pizza_hut,
        "policybazaar" to R.drawable.ic_brand_policybazaar,
        "practo" to R.drawable.ic_brand_practo,
        "punjab national bank" to R.drawable.ic_brand_punjab_national_bank,
        "pnb" to R.drawable.ic_brand_punjab_national_bank,
        "pvr" to R.drawable.ic_brand_pvr,
        "rapido" to R.drawable.ic_brand_rapido,
        "rbl bank" to R.drawable.ic_brand_rbl_bank,
        "redbus" to R.drawable.ic_brand_redbus,
        "sbi" to R.drawable.ic_brand_sbi,
        "state bank of india" to R.drawable.ic_brand_sbi,
        "sbi life" to R.drawable.ic_brand_sbi_life,
        "shopclues" to R.drawable.ic_brand_shopclues,
        "simpl" to R.drawable.ic_brand_simpl,
        "simplilearn" to R.drawable.ic_brand_simplilearn,
        "slack" to R.drawable.ic_brand_slack,
        "slice" to R.drawable.ic_brand_slice,
        "smallcase" to R.drawable.ic_brand_smallcase,
        "snapdeal" to R.drawable.ic_brand_snapdeal,
        "sony liv" to R.drawable.ic_brand_sony_liv,
        "spicejet" to R.drawable.ic_brand_spicejet,
        "spotify" to R.drawable.ic_brand_spotify,
        "starbucks" to R.drawable.ic_brand_starbucks,
        "sun direct" to R.drawable.ic_brand_sun_direct,
        "swiggy" to R.drawable.ic_brand_swiggy,
        "tata aia" to R.drawable.ic_brand_tata_aia,
        "tata power" to R.drawable.ic_brand_tata_power,
        "tata sky" to R.drawable.ic_brand_tata_sky,
        "the hindu" to R.drawable.ic_brand_the_hindu,
        "the times of india" to R.drawable.ic_brand_the_times_of_india,
        "tikona" to R.drawable.ic_brand_tikona,
        "timespoints" to R.drawable.ic_brand_timespoints,
        "toppr" to R.drawable.ic_brand_toppr,
        "truemeds" to R.drawable.ic_brand_truemeds,
        "uber" to R.drawable.ic_brand_uber,
        "udacity" to R.drawable.ic_brand_udacity,
        "udemy" to R.drawable.ic_brand_udemy,
        "unacademy" to R.drawable.ic_brand_unacademy,
        "union bank" to R.drawable.ic_brand_union_bank,
        "upgrad" to R.drawable.ic_brand_upgrad,
        "upstox" to R.drawable.ic_brand_upstox,
        "urban company" to R.drawable.ic_brand_urban_company,
        "urban ladder" to R.drawable.ic_brand_urban_ladder,
        "vedantu" to R.drawable.ic_brand_vedantu,
        "vistara" to R.drawable.ic_brand_vistara,
        "vodafone" to R.drawable.ic_brand_vodafone,
        "vodafone idea" to R.drawable.ic_brand_vodafone_idea,
        "vogo" to R.drawable.ic_brand_vogo,
        "voot" to R.drawable.ic_brand_voot,
        "whitehat jr" to R.drawable.ic_brand_whitehat_jr,
        "wynk" to R.drawable.ic_brand_wynk,
        "yatra" to R.drawable.ic_brand_yatra,
        "yes bank" to R.drawable.ic_brand_yes_bank,
        "youtube" to R.drawable.ic_brand_youtube,
        "yulu" to R.drawable.ic_brand_yulu,
        "zee5" to R.drawable.ic_brand_zee5,
        "zepto" to R.drawable.ic_brand_zepto,
        "zerodha" to R.drawable.ic_brand_zerodha,
        "zomato" to R.drawable.ic_brand_zomato,
        "zoom" to R.drawable.ic_brand_zoom,
        "mbank" to R.drawable.ic_brand_mbank_cz,
        "al rajhi bank" to R.drawable.ic_brand_al_rajhi_bank,
        "chase" to R.drawable.ic_brand_chase_bank,
        "tbank" to R.drawable.ic_brand_tbank,
        "t-bank" to R.drawable.ic_brand_tbank,
        "everest bank" to R.drawable.ic_brand_everest_bank,
        "au bank" to R.drawable.ic_brand_au_bank,
        "au small finance" to R.drawable.ic_brand_au_bank,
        // Banks - Indian
        "saraswat bank" to R.drawable.ic_brand_saraswat_bank,
        "indian bank" to R.drawable.ic_brand_indian_bank,
        "karnataka bank" to R.drawable.ic_brand_karnataka_bank,
        "kerala gramin bank" to R.drawable.ic_brand_kerala_gramin_bank,
        "jupiter" to R.drawable.ic_brand_jupiter_bank,
        "bank of india" to R.drawable.ic_brand_bank_of_india,
        "hsbc" to R.drawable.ic_brand_hsbc_bank,
        "central bank of india" to R.drawable.ic_brand_central_bank_of_india,
        "south indian bank" to R.drawable.ic_brand_south_indian_bank,
        "city union bank" to R.drawable.ic_brand_city_union_bank,
        "indian overseas bank" to R.drawable.ic_brand_indian_overseas_bank,
        "iob" to R.drawable.ic_brand_indian_overseas_bank,
        "standard chartered" to R.drawable.ic_brand_standard_chartered,
        "equitas" to R.drawable.ic_brand_equitas_bank,
        "dhanlaxmi bank" to R.drawable.ic_brand_dhanlaxmi_bank,
        "jk bank" to R.drawable.ic_brand_jk_bank,
        "jammu & kashmir bank" to R.drawable.ic_brand_jk_bank,
        "idbi bank" to R.drawable.ic_brand_idbi,
        "idbi" to R.drawable.ic_brand_idbi,
        "kotak bank" to R.drawable.ic_brand_kotak_mahindra_bank,
        "nsdl payments bank" to R.drawable.ic_brand_nsdl_payments_bank,
        "onecard" to R.drawable.ic_brand_onecard,
        "punjab & sind bank" to R.drawable.ic_brand_punjab_sind_bank,
        "punjab and sind bank" to R.drawable.ic_brand_punjab_sind_bank,
        "uco bank" to R.drawable.ic_brand_uco_bank,
        "utkarsh bank" to R.drawable.ic_brand_utkarsh_bank,
        "kerala bank" to R.drawable.ic_brand_kerela_bank,
        // Banks - Indian Fintech/Payments
        "juspay" to R.drawable.ic_brand_juspay,
        "india post payments bank" to R.drawable.ic_brand_ippb,
        "ippb" to R.drawable.ic_brand_ippb,
        "cashfree" to R.drawable.ic_brand_cashfree,
        "navi mutual fund" to R.drawable.ic_brand_navi_mutual_funds,
        "navi" to R.drawable.ic_brand_navi_mutual_funds,
        "hdfc mutual fund" to R.drawable.ic_brand_hdfc_mutual_funds,
        // Banks - Credit Cards
        "american express" to R.drawable.ic_brand_amex,
        "amex" to R.drawable.ic_brand_amex,
        // Banks - UAE
        "adcb" to R.drawable.ic_brand_adcb,
        "abu dhabi commercial bank" to R.drawable.ic_brand_adcb,
        "first abu dhabi" to R.drawable.ic_brand_fab_bank,
        "fab bank" to R.drawable.ic_brand_fab_bank,
        "emirates nbd" to R.drawable.ic_brand_emirates_nbd,
        "emirates islamic" to R.drawable.ic_brand_emirates_islamic,
        "liv bank" to R.drawable.ic_brand_liv_bank,
        "mashreq" to R.drawable.ic_brand_mashreq_bank,
        // Banks - USA
        "citi bank" to R.drawable.ic_brand_citi_bank,
        "citibank" to R.drawable.ic_brand_citi_bank,
        "discover" to R.drawable.ic_brand_discover,
        "charles schwab" to R.drawable.ic_brand_charles_schwab,
        "schwab" to R.drawable.ic_brand_charles_schwab,
        "navy federal" to R.drawable.ic_brand_navy_federal,
        "huntington bank" to R.drawable.ic_brand_huntington_bank,
        "huntington" to R.drawable.ic_brand_huntington_bank,
        "adelfi" to R.drawable.ic_brand_adelfi,
        "altana fcu" to R.drawable.ic_brand_altana_fcu,
        "old hickory" to R.drawable.ic_brand_old_hickory,
        "old hickory credit union" to R.drawable.ic_brand_old_hickory,
        // Banks - Nepal
        "laxmi sunrise" to R.drawable.ic_brand_laxmi_sunrise_bank,
        "nmb bank" to R.drawable.ic_brand_nmb_bank,
        "nabil bank" to R.drawable.ic_brand_nabil_bank,
        "nabil" to R.drawable.ic_brand_nabil_bank,
        "manjushree finance" to R.drawable.ic_brand_manjushree_finance,
        "siddhartha bank" to R.drawable.ic_brand_siddhartha_bank,
        // Banks - Africa / Mobile Money
        "m-pesa" to R.drawable.ic_brand_mpesa,
        "mpesa" to R.drawable.ic_brand_mpesa,
        "selcom" to R.drawable.ic_brand_selcom_pesa,
        "tigo pesa" to R.drawable.ic_brand_tigo_pesa,
        "commercial bank of ethiopia" to R.drawable.ic_brand_cbe_bank,
        // Banks - Other International
        "dbs bank" to R.drawable.ic_brand_dbs_bank,
        "dbs" to R.drawable.ic_brand_dbs_bank,
        "bancolombia" to R.drawable.ic_brand_bancolombia,
        "priorbank" to R.drawable.ic_brand_priorbank,
        "alinma" to R.drawable.ic_brand_alinma_bank,
        "cib egypt" to R.drawable.ic_brand_cib_egypt,
        "bpce" to R.drawable.ic_brand_bpce_bank,
        "caisse d'epargne" to R.drawable.ic_brand_bpce_bank,
        "alecu" to R.drawable.ic_brand_alecu_bank,
        "bank muscat" to R.drawable.ic_brand_bank_muscat,
        "telebirr" to R.drawable.ic_brand_telebirr,
        "access bank" to R.drawable.ic_brand_access_bank,
        "arab bank" to R.drawable.ic_brand_arab_bank,
        "baac" to R.drawable.ic_brand_baac,
        "bangkok bank" to R.drawable.ic_brand_bangkok_bank,
        "bankino" to R.drawable.ic_brand_bankino,
        "blu bank" to R.drawable.ic_brand_blu_bank,
        "cimb thai" to R.drawable.ic_brand_cimb,
        "cimb" to R.drawable.ic_brand_cimb,
        "crdb bank" to R.drawable.ic_brand_crdb,
        "dashen bank" to R.drawable.ic_brand_dashen_bank,
        "diamond trust bank" to R.drawable.ic_brand_diamond_trust,
        "e-mola" to R.drawable.ic_brand_e_mola,
        "enpara bank" to R.drawable.ic_brand_enpara,
        "faysal bank" to R.drawable.ic_brand_faysal_bank,
        "greater bank" to R.drawable.ic_brand_greater_bank,
        "government savings bank" to R.drawable.ic_brand_gsb,
        "gsb" to R.drawable.ic_brand_gsb,
        "jaiz bank" to R.drawable.ic_brand_jaiz_bank,
        "kasikorn bank" to R.drawable.ic_brand_kasikorn_bank,
        "keystone bank" to R.drawable.ic_brand_keystone_bank,
        "krungsri" to R.drawable.ic_brand_krungsri,
        "krungthai bank" to R.drawable.ic_brand_krungthai,
        "krungthai" to R.drawable.ic_brand_krungthai,
        "ktc" to R.drawable.ic_brand_ktc,
        "mellat bank" to R.drawable.ic_brand_mellat_bank,
        "melli bank" to R.drawable.ic_brand_melli_bank,
        "millennium bim" to R.drawable.ic_brand_millennium_bim,
        "mixx by yas" to R.drawable.ic_brand_mixx_by_yas,
        "nmb tanzania" to R.drawable.ic_brand_nmb_tanzania,
        "opay" to R.drawable.ic_brand_0pay,
        "0pay" to R.drawable.ic_brand_0pay,
        "parsian bank" to R.drawable.ic_brand_parsian_bank,
        "sabb bank" to R.drawable.ic_brand_sabb_bank,
        "sampath bank" to R.drawable.ic_brand_sampath_bank,
        "siam commercial bank" to R.drawable.ic_brand_siam_commercial,
        "snb al ahli" to R.drawable.ic_brand_snb_alahli,
        "sparkasse" to R.drawable.ic_brand_sparkasse_rhein_maas,
        "sparkasse rhein-maas" to R.drawable.ic_brand_sparkasse_rhein_maas,
        "standard bank" to R.drawable.ic_brand_standard_bank,
        "standard bank mozambique" to R.drawable.ic_brand_standard_bank,
        "stc bank" to R.drawable.ic_brand_stc_bank,
        "ttb" to R.drawable.ic_brand_ttb,
        "uob thailand" to R.drawable.ic_brand_uob,
        "uob" to R.drawable.ic_brand_uob,
        "zemen bank" to R.drawable.ic_brand_zemen_bank,
        "zenith bank" to R.drawable.ic_brand_zenith_bank,
        // Additional brands
        "airbnb" to R.drawable.ic_brand_airbnb,
        "apple tv" to R.drawable.ic_brand_apple_tv,
        "bumble" to R.drawable.ic_brand_bumble,
        "chatgpt" to R.drawable.ic_brand_chatgpt,
        "claude" to R.drawable.ic_brand_claude,
        "crunchyroll" to R.drawable.ic_brand_crunchyroll,
        "disney plus" to R.drawable.ic_brand_disney_plus,
        "fastag" to R.drawable.ic_brand_fastag,
        "gemini" to R.drawable.ic_brand_gemini,
        "google pay" to R.drawable.ic_brand_google_pay,
        "google play" to R.drawable.ic_brand_google_play,
        "google" to R.drawable.ic_brand_google,
        "grok" to R.drawable.ic_brand_grok,
        "hbo max" to R.drawable.ic_brand_hbo_max,
        "jiocinema" to R.drawable.ic_brand_jiocinema,
        "jiohotstar" to R.drawable.ic_brand_jiohotstar,
        "oyo" to R.drawable.ic_brand_oyo,
        "perplexity" to R.drawable.ic_brand_perplexity,
        "playstation" to R.drawable.ic_brand_playstation,
        "proton vpn" to R.drawable.ic_brand_proton_vpn,
        "visa" to R.drawable.ic_brand_visa,
        "xbox" to R.drawable.ic_brand_xbox,
        "youtube music" to R.drawable.ic_brand_youtube_music,
        "x" to R.drawable.ic_brand_x,
    )
    
    fun getIconResource(merchantName: String): Int? {
        InstitutionCatalog.find(merchantName)?.let { return it.iconResId }
        val normalized = merchantName.lowercase()

        if (normalized.contains("cred") && !normalized.contains("credit")) {
            brandMappings["cred"]?.let { return it }
        }

        return brandMappings.entries
            .sortedByDescending { it.key.length }
            .firstOrNull { (key, _) ->
                key != "cred" && normalized.contains(key)
            }
            ?.value
    }
    
    fun getBrandColor(merchantName: String): String? = InstitutionCatalog.find(merchantName)?.color ?: when {
        // Entertainment
        merchantName.contains("netflix", ignoreCase = true) -> "#E50914"
        merchantName.contains("spotify", ignoreCase = true) -> "#1DB954"
        merchantName.contains("youtube", ignoreCase = true) -> "#FF0000"
        merchantName.contains("disney", ignoreCase = true) -> "#113CCF"
        merchantName.contains("sony", ignoreCase = true) -> "#000000"
        merchantName.contains("zee", ignoreCase = true) -> "#6C2E91"
        merchantName.contains("voot", ignoreCase = true) -> "#E5007E"
        
        // Food
        merchantName.contains("swiggy", ignoreCase = true) -> "#FC8019"
        merchantName.contains("zomato", ignoreCase = true) -> "#E23744"
        merchantName.contains("blinkit", ignoreCase = true) -> "#FFC800"
        merchantName.contains("zepto", ignoreCase = true) -> "#9B51E0"
        merchantName.contains("dominos", ignoreCase = true) -> "#0066B3"
        merchantName.contains("mcdonalds", ignoreCase = true) -> "#FFC600"
        merchantName.contains("kfc", ignoreCase = true) -> "#F40027"
        merchantName.contains("starbucks", ignoreCase = true) -> "#00704A"
        
        // Banks
        merchantName.contains("hdfc", ignoreCase = true) -> "#004C8F"
        merchantName.contains("icici", ignoreCase = true) -> "#F37021"
        merchantName.contains("axis", ignoreCase = true) -> "#97144D"
        merchantName.contains("sbi", ignoreCase = true) || 
        merchantName.contains("state bank of india", ignoreCase = true) -> "#22409A"
        merchantName.contains("kotak", ignoreCase = true) -> "#EF3829"
        merchantName.contains("yes bank", ignoreCase = true) -> "#0066CC"
        merchantName.contains("idfc", ignoreCase = true) -> "#8B0000"
        merchantName.contains("indusind", ignoreCase = true) -> "#98272B"
        merchantName.contains("pnb", ignoreCase = true) -> "#0E2B5C"
        merchantName.contains("prime commercial bank", ignoreCase = true) -> "#0054A6"
        merchantName.contains("mbank", ignoreCase = true) -> "#ED1C24"
        merchantName.contains("al rajhi", ignoreCase = true) -> "#0066CC"
        merchantName.contains("chase", ignoreCase = true) -> "#117ACA"
        merchantName.contains("nabil", ignoreCase = true) -> "#25A64C"
        merchantName.contains("manjushree", ignoreCase = true) -> "#EF2F1A"
        merchantName.contains("tbank", ignoreCase = true) || 
        merchantName.contains("t-bank", ignoreCase = true) ||
        merchantName.contains("tinkoff", ignoreCase = true) -> "#FFDD2D"
        merchantName.contains("everest bank", ignoreCase = true) -> "#ED1C24"
        merchantName.contains("au bank", ignoreCase = true) -> "#EC6608"
        merchantName.contains("hsbc", ignoreCase = true) -> "#DB0011"
        merchantName.contains("standard chartered", ignoreCase = true) -> "#0072AA"
        merchantName.contains("dbs", ignoreCase = true) -> "#E21A1A"
        merchantName.contains("amex", ignoreCase = true) || 
        merchantName.contains("american express", ignoreCase = true) -> "#006FCF"
        merchantName.contains("citi", ignoreCase = true) -> "#003B70"
        merchantName.contains("emirates nbd", ignoreCase = true) -> "#003366"
        merchantName.contains("mashreq", ignoreCase = true) -> "#ED1C24"
        merchantName.contains("adcb", ignoreCase = true) -> "#00263E"
        merchantName.contains("navy federal", ignoreCase = true) -> "#003468"
        merchantName.contains("huntington", ignoreCase = true) -> "#00703C"
        merchantName.contains("m-pesa", ignoreCase = true) || 
        merchantName.contains("mpesa", ignoreCase = true) -> "#4DB848"
        merchantName.contains("bancolombia", ignoreCase = true) -> "#FDDA24"
        merchantName.contains("jupiter", ignoreCase = true) -> "#F26B5B"
        merchantName.contains("equitas", ignoreCase = true) -> "#ED1C24"
        merchantName.contains("discover", ignoreCase = true) -> "#FF6000"
        merchantName.contains("schwab", ignoreCase = true) -> "#00A0DF"
        merchantName.contains("alinma", ignoreCase = true) -> "#B8964B"
        merchantName.contains("bpce", ignoreCase = true) || 
        merchantName.contains("caisse d'epargne", ignoreCase = true) -> "#642D8E"
        merchantName.contains("alecu", ignoreCase = true) -> "#003056"
        merchantName.contains("bank muscat", ignoreCase = true) -> "#003B71"
        merchantName.contains("telebirr", ignoreCase = true) -> "#E11B22"
        
        // Payments
        merchantName.contains("paytm", ignoreCase = true) -> "#00B9F1"
        merchantName.contains("phonepe", ignoreCase = true) -> "#5F259F"
        merchantName.contains("google pay", ignoreCase = true) -> "#4285F4"
        merchantName.contains("cred", ignoreCase = true) -> "#000000"
        merchantName.contains("amazon pay", ignoreCase = true) -> "#FF9900"
        
        // Telecom
        merchantName.contains("airtel", ignoreCase = true) -> "#E52E2D"
        merchantName.contains("jio", ignoreCase = true) -> "#2A3890"
        merchantName.contains("vodafone", ignoreCase = true) -> "#E60000"
        merchantName.contains("idea", ignoreCase = true) -> "#FDD922"
        merchantName.contains("bsnl", ignoreCase = true) -> "#0078BF"
        
        // Shopping
        merchantName.contains("amazon", ignoreCase = true) -> "#FF9900"
        merchantName.contains("flipkart", ignoreCase = true) -> "#027CD5"
        merchantName.contains("myntra", ignoreCase = true) -> "#FF3F6C"
        merchantName.contains("ajio", ignoreCase = true) -> "#2C4152"
        merchantName.contains("nykaa", ignoreCase = true) -> "#FC2779"
        merchantName.contains("meesho", ignoreCase = true) -> "#F43397"
        
        // Transport
        merchantName.contains("uber", ignoreCase = true) -> "#000000"
        merchantName.contains("ola", ignoreCase = true) -> "#93CE25"
        merchantName.contains("rapido", ignoreCase = true) -> "#FFC800"
        merchantName.contains("irctc", ignoreCase = true) -> "#FB792B"
        
        // Investment
        merchantName.contains("groww", ignoreCase = true) -> "#00D09C"
        merchantName.contains("zerodha", ignoreCase = true) -> "#387ED1"
        merchantName.contains("upstox", ignoreCase = true) -> "#5E72E4"
        merchantName.contains("angel", ignoreCase = true) -> "#5B2D90"
        
        // Medical
        merchantName.contains("1mg", ignoreCase = true) -> "#FC574E"
        merchantName.contains("pharmeasy", ignoreCase = true) -> "#10847E"
        merchantName.contains("netmeds", ignoreCase = true) -> "#24AEB1"
        merchantName.contains("apollo", ignoreCase = true) -> "#0066B3"
        merchantName.contains("practo", ignoreCase = true) -> "#1EBEA5"
        
        // Fitness
        merchantName.contains("cult", ignoreCase = true) -> "#FF3278"
        merchantName.contains("gym", ignoreCase = true) -> "#F15B2A"

        // Additional brands
        merchantName.contains("airbnb", ignoreCase = true) -> "#FF5A5F"
        merchantName.contains("apple tv", ignoreCase = true) -> "#000000"
        merchantName.contains("bumble", ignoreCase = true) -> "#FFC000"
        merchantName.contains("chatgpt", ignoreCase = true) -> "#74AA9C"
        merchantName.contains("claude", ignoreCase = true) -> "#D97757"
        merchantName.contains("crunchyroll", ignoreCase = true) -> "#F47521"
        merchantName.contains("disney plus", ignoreCase = true) -> "#113CCF"
        merchantName.contains("fastag", ignoreCase = true) -> "#F79620"
        merchantName.contains("gemini", ignoreCase = true) -> "#1A73E8"
        merchantName.contains("grok", ignoreCase = true) -> "#000000"
        merchantName.contains("hbo max", ignoreCase = true) -> "#5822B4"
        merchantName.contains("jiocinema", ignoreCase = true) -> "#E50914"
        merchantName.contains("jiohotstar", ignoreCase = true) -> "#E50914"
        merchantName.contains("oyo", ignoreCase = true) -> "#2C3E50"
        merchantName.contains("perplexity", ignoreCase = true) -> "#1E3A5F"
        merchantName.contains("playstation", ignoreCase = true) -> "#003791"
        merchantName.contains("proton vpn", ignoreCase = true) -> "#6D4AFF"
        merchantName.contains("visa", ignoreCase = true) -> "#1A1F71"
        merchantName.contains("xbox", ignoreCase = true) -> "#107C10"
        merchantName.contains("youtube music", ignoreCase = true) -> "#FF0000"

        else -> null
    }
}
