// Auto-generated by fetch_logos.py
package com.ritesh.cashiro.presentation.common.icons

import com.ritesh.cashiro.R

object BrandIcons {
    private val brandMappings = mapOf(
        "amazon" to R.drawable.ic_brand_amazon,
        "amazon prime" to R.drawable.ic_brand_amazon_prime,
        "anytime fitness" to R.drawable.ic_brand_anytime_fitness,
        "apple music" to R.drawable.ic_brand_apple_music,
        "burger king" to R.drawable.ic_brand_burger_king,
        "cinepolis" to R.drawable.ic_brand_cinepolis,
        "coursera" to R.drawable.ic_brand_coursera,
        "dominos" to R.drawable.ic_brand_dominos,
        "golds gym" to R.drawable.ic_brand_golds_gym,
        "kfc" to R.drawable.ic_brand_kfc,
        "mcdonalds" to R.drawable.ic_brand_mcdonalds,
        "microsoft teams" to R.drawable.ic_brand_microsoft_teams,
        "netflix" to R.drawable.ic_brand_netflix,
        "prime commercial bank" to R.drawable.ic_brand_prime_commercial_bank,
        "pizza hut" to R.drawable.ic_brand_pizza_hut,
        "slack" to R.drawable.ic_brand_slack,
        "spotify" to R.drawable.ic_brand_spotify,
        "starbucks" to R.drawable.ic_brand_starbucks,
        "uber" to R.drawable.ic_brand_uber,
        "udacity" to R.drawable.ic_brand_udacity,
        "udemy" to R.drawable.ic_brand_udemy,
        "vodafone" to R.drawable.ic_brand_vodafone,
        "youtube" to R.drawable.ic_brand_youtube,
        "zoom" to R.drawable.ic_brand_zoom,
        "mbank" to R.drawable.ic_brand_mbank_cz,
        "al rajhi bank" to R.drawable.ic_brand_al_rajhi_bank,
        "chase" to R.drawable.ic_brand_chase_bank,
        "tbank" to R.drawable.ic_brand_tbank,
        "t-bank" to R.drawable.ic_brand_tbank,
        "everest bank" to R.drawable.ic_brand_everest_bank,
        // Banks - Indian
        "hsbc" to R.drawable.ic_brand_hsbc_bank,
        "standard chartered" to R.drawable.ic_brand_standard_chartered,
        // Banks - Indian Fintech/Payments
        // Banks - Credit Cards
        "american express" to R.drawable.ic_brand_amex,
        "amex" to R.drawable.ic_brand_amex,
        // Banks - UAE
        "adcb" to R.drawable.ic_brand_adcb,
        "abu dhabi commercial bank" to R.drawable.ic_brand_adcb,
        "first abu dhabi" to R.drawable.ic_brand_fab_bank,
        "fab bank" to R.drawable.ic_brand_fab_bank,
        "emirates nbd" to R.drawable.ic_brand_emirates_nbd,
        "emirates islamic" to R.drawable.ic_brand_emirates_islamic,
        "liv bank" to R.drawable.ic_brand_liv_bank,
        "mashreq" to R.drawable.ic_brand_mashreq_bank,
        // Banks - USA
        "citi bank" to R.drawable.ic_brand_citi_bank,
        "citibank" to R.drawable.ic_brand_citi_bank,
        "discover" to R.drawable.ic_brand_discover,
        "charles schwab" to R.drawable.ic_brand_charles_schwab,
        "schwab" to R.drawable.ic_brand_charles_schwab,
        "navy federal" to R.drawable.ic_brand_navy_federal,
        "huntington bank" to R.drawable.ic_brand_huntington_bank,
        "huntington" to R.drawable.ic_brand_huntington_bank,
        "adelfi" to R.drawable.ic_brand_adelfi,
        "altana fcu" to R.drawable.ic_brand_altana_fcu,
        "old hickory" to R.drawable.ic_brand_old_hickory,
        "old hickory credit union" to R.drawable.ic_brand_old_hickory,
        // Banks - Nepal
        "laxmi sunrise" to R.drawable.ic_brand_laxmi_sunrise_bank,
        "nmb bank" to R.drawable.ic_brand_nmb_bank,
        "nabil bank" to R.drawable.ic_brand_nabil_bank,
        "nabil" to R.drawable.ic_brand_nabil_bank,
        "manjushree finance" to R.drawable.ic_brand_manjushree_finance,
        "siddhartha bank" to R.drawable.ic_brand_siddhartha_bank,
        // Banks - Africa / Mobile Money
        "m-pesa" to R.drawable.ic_brand_mpesa,
        "mpesa" to R.drawable.ic_brand_mpesa,
        "selcom" to R.drawable.ic_brand_selcom_pesa,
        "tigo pesa" to R.drawable.ic_brand_tigo_pesa,
        "commercial bank of ethiopia" to R.drawable.ic_brand_cbe_bank,
        // Banks - Other International
        "dbs bank" to R.drawable.ic_brand_dbs_bank,
        "dbs" to R.drawable.ic_brand_dbs_bank,
        "bancolombia" to R.drawable.ic_brand_bancolombia,
        "priorbank" to R.drawable.ic_brand_priorbank,
        "alinma" to R.drawable.ic_brand_alinma_bank,
        "cib egypt" to R.drawable.ic_brand_cib_egypt,
        "bpce" to R.drawable.ic_brand_bpce_bank,
        "caisse d'epargne" to R.drawable.ic_brand_bpce_bank,
        "alecu" to R.drawable.ic_brand_alecu_bank,
        "bank muscat" to R.drawable.ic_brand_bank_muscat,
        "telebirr" to R.drawable.ic_brand_telebirr,
        "access bank" to R.drawable.ic_brand_access_bank,
        "arab bank" to R.drawable.ic_brand_arab_bank,
        "baac" to R.drawable.ic_brand_baac,
        "bangkok bank" to R.drawable.ic_brand_bangkok_bank,
        "bankino" to R.drawable.ic_brand_bankino,
        "blu bank" to R.drawable.ic_brand_blu_bank,
        "cimb thai" to R.drawable.ic_brand_cimb,
        "cimb" to R.drawable.ic_brand_cimb,
        "crdb bank" to R.drawable.ic_brand_crdb,
        "dashen bank" to R.drawable.ic_brand_dashen_bank,
        "diamond trust bank" to R.drawable.ic_brand_diamond_trust,
        "e-mola" to R.drawable.ic_brand_e_mola,
        "enpara bank" to R.drawable.ic_brand_enpara,
        "faysal bank" to R.drawable.ic_brand_faysal_bank,
        "greater bank" to R.drawable.ic_brand_greater_bank,
        "jaiz bank" to R.drawable.ic_brand_jaiz_bank,
        "kasikorn bank" to R.drawable.ic_brand_kasikorn_bank,
        "keystone bank" to R.drawable.ic_brand_keystone_bank,
        "krungsri" to R.drawable.ic_brand_krungsri,
        "krungthai bank" to R.drawable.ic_brand_krungthai,
        "krungthai" to R.drawable.ic_brand_krungthai,
        "ktc" to R.drawable.ic_brand_ktc,
        "mellat bank" to R.drawable.ic_brand_mellat_bank,
        "melli bank" to R.drawable.ic_brand_melli_bank,
        "millennium bim" to R.drawable.ic_brand_millennium_bim,
        "mixx by yas" to R.drawable.ic_brand_mixx_by_yas,
        "nmb tanzania" to R.drawable.ic_brand_nmb_tanzania,
        "opay" to R.drawable.ic_brand_0pay,
        "0pay" to R.drawable.ic_brand_0pay,
        "parsian bank" to R.drawable.ic_brand_parsian_bank,
        "sabb bank" to R.drawable.ic_brand_sabb_bank,
        "sampath bank" to R.drawable.ic_brand_sampath_bank,
        "siam commercial bank" to R.drawable.ic_brand_siam_commercial,
        "snb al ahli" to R.drawable.ic_brand_snb_alahli,
        "sparkasse" to R.drawable.ic_brand_sparkasse_rhein_maas,
        "sparkasse rhein-maas" to R.drawable.ic_brand_sparkasse_rhein_maas,
        "standard bank" to R.drawable.ic_brand_standard_bank,
        "standard bank mozambique" to R.drawable.ic_brand_standard_bank,
        "stc bank" to R.drawable.ic_brand_stc_bank,
        "ttb" to R.drawable.ic_brand_ttb,
        "uob thailand" to R.drawable.ic_brand_uob,
        "uob" to R.drawable.ic_brand_uob,
        "zemen bank" to R.drawable.ic_brand_zemen_bank,
        "zenith bank" to R.drawable.ic_brand_zenith_bank,
        // Additional brands
        "airbnb" to R.drawable.ic_brand_airbnb,
        "apple tv" to R.drawable.ic_brand_apple_tv,
        "bumble" to R.drawable.ic_brand_bumble,
        "chatgpt" to R.drawable.ic_brand_chatgpt,
        "claude" to R.drawable.ic_brand_claude,
        "crunchyroll" to R.drawable.ic_brand_crunchyroll,
        "disney plus" to R.drawable.ic_brand_disney_plus,
        "gemini" to R.drawable.ic_brand_gemini,
        "google pay" to R.drawable.ic_brand_google_pay,
        "google play" to R.drawable.ic_brand_google_play,
        "google" to R.drawable.ic_brand_google,
        "grok" to R.drawable.ic_brand_grok,
        "hbo max" to R.drawable.ic_brand_hbo_max,
        "perplexity" to R.drawable.ic_brand_perplexity,
        "playstation" to R.drawable.ic_brand_playstation,
        "proton vpn" to R.drawable.ic_brand_proton_vpn,
        "visa" to R.drawable.ic_brand_visa,
        "xbox" to R.drawable.ic_brand_xbox,
        "youtube music" to R.drawable.ic_brand_youtube_music,
        "x" to R.drawable.ic_brand_x,
        // Chinese brands and Chinese names (vector logos from Simple Icons)
        "支付宝" to R.drawable.ic_brand_alipay,
        "alipay" to R.drawable.ic_brand_alipay,
        "花呗" to R.drawable.ic_brand_alipay,
        "余额宝" to R.drawable.ic_brand_alipay,
        "微信" to R.drawable.ic_brand_wechat,
        "wechat" to R.drawable.ic_brand_wechat,
        "weixin" to R.drawable.ic_brand_wechat,
        "财付通" to R.drawable.ic_brand_wechat,
        "tenpay" to R.drawable.ic_brand_wechat,
        "美团" to R.drawable.ic_brand_meituan,
        "meituan" to R.drawable.ic_brand_meituan,
        "大众点评" to R.drawable.ic_brand_dianping,
        "dianping" to R.drawable.ic_brand_dianping,
        "淘宝" to R.drawable.ic_brand_taobao,
        "taobao" to R.drawable.ic_brand_taobao,
        "天猫" to R.drawable.ic_brand_taobao,
        "tmall" to R.drawable.ic_brand_taobao,
        "速卖通" to R.drawable.ic_brand_aliexpress,
        "aliexpress" to R.drawable.ic_brand_aliexpress,
        "阿里云" to R.drawable.ic_brand_alibaba_cloud,
        "aliyun" to R.drawable.ic_brand_alibaba_cloud,
        "alibaba cloud" to R.drawable.ic_brand_alibaba_cloud,
        "小红书" to R.drawable.ic_brand_xiaohongshu,
        "xiaohongshu" to R.drawable.ic_brand_xiaohongshu,
        "rednote" to R.drawable.ic_brand_xiaohongshu,
        "哔哩哔哩" to R.drawable.ic_brand_bilibili,
        "bilibili" to R.drawable.ic_brand_bilibili,
        "b站" to R.drawable.ic_brand_bilibili,
        "抖音" to R.drawable.ic_brand_douyin,
        "douyin" to R.drawable.ic_brand_douyin,
        "tiktok" to R.drawable.ic_brand_douyin,
        "快手" to R.drawable.ic_brand_kuaishou,
        "kuaishou" to R.drawable.ic_brand_kuaishou,
        "腾讯" to R.drawable.ic_brand_qq,
        "tencent" to R.drawable.ic_brand_qq,
        "qq" to R.drawable.ic_brand_qq,
        "网易云音乐" to R.drawable.ic_brand_netease_cloud_music,
        "netease cloud music" to R.drawable.ic_brand_netease_cloud_music,
        "网易云" to R.drawable.ic_brand_netease_cloud_music,
        "知乎" to R.drawable.ic_brand_zhihu,
        "zhihu" to R.drawable.ic_brand_zhihu,
        "微博" to R.drawable.ic_brand_weibo,
        "weibo" to R.drawable.ic_brand_weibo,
        "百度" to R.drawable.ic_brand_baidu,
        "baidu" to R.drawable.ic_brand_baidu,
        "携程" to R.drawable.ic_brand_trip_com,
        "ctrip" to R.drawable.ic_brand_trip_com,
        "trip.com" to R.drawable.ic_brand_trip_com,
        "12306" to R.drawable.ic_brand_china_railway,
        "中国铁路" to R.drawable.ic_brand_china_railway,
        "铁路" to R.drawable.ic_brand_china_railway,
        "china railway" to R.drawable.ic_brand_china_railway,
        "中国国际航空" to R.drawable.ic_brand_air_china,
        "国航" to R.drawable.ic_brand_air_china,
        "air china" to R.drawable.ic_brand_air_china,
        "东方航空" to R.drawable.ic_brand_china_eastern,
        "东航" to R.drawable.ic_brand_china_eastern,
        "china eastern" to R.drawable.ic_brand_china_eastern,
        "南方航空" to R.drawable.ic_brand_china_southern,
        "南航" to R.drawable.ic_brand_china_southern,
        "china southern" to R.drawable.ic_brand_china_southern,
        "小米" to R.drawable.ic_brand_xiaomi,
        "xiaomi" to R.drawable.ic_brand_xiaomi,
        "华为" to R.drawable.ic_brand_huawei,
        "huawei" to R.drawable.ic_brand_huawei,
        "苹果" to R.drawable.ic_brand_apple,
        "apple.com" to R.drawable.ic_brand_apple,
        "apple store" to R.drawable.ic_brand_apple,
        "apple" to R.drawable.ic_brand_apple,
        "app store" to R.drawable.ic_brand_app_store,
        "appstore" to R.drawable.ic_brand_app_store,
        "icloud" to R.drawable.ic_brand_icloud,
        "steam" to R.drawable.ic_brand_steam,
        "github" to R.drawable.ic_brand_github,
        "anthropic" to R.drawable.ic_brand_anthropic,
        "特斯拉" to R.drawable.ic_brand_tesla,
        "tesla" to R.drawable.ic_brand_tesla,
        "山姆" to R.drawable.ic_brand_sams_club,
        "sam's club" to R.drawable.ic_brand_sams_club,
        "sams club" to R.drawable.ic_brand_sams_club,
        "宜家" to R.drawable.ic_brand_ikea,
        "ikea" to R.drawable.ic_brand_ikea,
        "优衣库" to R.drawable.ic_brand_uniqlo,
        "uniqlo" to R.drawable.ic_brand_uniqlo,
        "耐克" to R.drawable.ic_brand_nike,
        "nike" to R.drawable.ic_brand_nike,
        "阿迪达斯" to R.drawable.ic_brand_adidas,
        "adidas" to R.drawable.ic_brand_adidas,
        "星巴克" to R.drawable.ic_brand_starbucks,
        "麦当劳" to R.drawable.ic_brand_mcdonalds,
        "肯德基" to R.drawable.ic_brand_kfc,
        "汉堡王" to R.drawable.ic_brand_burger_king,
        "必胜客" to R.drawable.ic_brand_pizza_hut,
        "奈飞" to R.drawable.ic_brand_netflix,
        "apple music" to R.drawable.ic_brand_apple_music,
        "优步" to R.drawable.ic_brand_uber,
        "爱彼迎" to R.drawable.ic_brand_airbnb,
        "达美乐" to R.drawable.ic_brand_dominos,
        "油管" to R.drawable.ic_brand_youtube,
        "亚马逊" to R.drawable.ic_brand_amazon,
        "汇丰" to R.drawable.ic_brand_hsbc_bank,
        "渣打" to R.drawable.ic_brand_standard_chartered,
        "花旗" to R.drawable.ic_brand_citi_bank,
        "星展" to R.drawable.ic_brand_dbs_bank,
        "大华银行" to R.drawable.ic_brand_uob,
        "openai" to R.drawable.ic_brand_chatgpt,
        "谷歌" to R.drawable.ic_brand_google,
    )
    
    // Immutable mapping: preserve longest-match precedence without sorting per row.
    private val longestBrandMatches: List<Pair<(String) -> Boolean, Int>> =
        brandMappings.entries.sortedByDescending { it.key.length }.map { (key, resId) -> matcher(key) to resId }

    /** Short Latin keys ("x", "qq") must stand alone, or "Exxon" would get the X logo. */
    private fun matcher(key: String): (String) -> Boolean {
        if (key.length > 3 || key.any { it.code > 0x7F }) return { name -> name.contains(key) }
        val word = Regex("(?<![a-z0-9])${Regex.escape(key)}(?![a-z0-9])")
        return { name -> word.containsMatchIn(name) }
    }

    fun getIconResource(merchantName: String): Int? {
        InstitutionCatalog.find(merchantName)?.let { return it.iconResId }
        val normalized = merchantName.lowercase()
        return longestBrandMatches.firstOrNull { (matches, _) -> matches(normalized) }?.second
    }
    
    fun getBrandColor(merchantName: String): String? = InstitutionCatalog.find(merchantName)?.color ?: when {
        // Entertainment
        merchantName.contains("netflix", ignoreCase = true) -> "#E50914"
        merchantName.contains("spotify", ignoreCase = true) -> "#1DB954"
        merchantName.contains("youtube", ignoreCase = true) -> "#FF0000"
        merchantName.contains("disney", ignoreCase = true) -> "#113CCF"
        merchantName.contains("sony", ignoreCase = true) -> "#000000"
        merchantName.contains("zee", ignoreCase = true) -> "#6C2E91"
        merchantName.contains("voot", ignoreCase = true) -> "#E5007E"
        
        // Food
        merchantName.contains("swiggy", ignoreCase = true) -> "#FC8019"
        merchantName.contains("zomato", ignoreCase = true) -> "#E23744"
        merchantName.contains("blinkit", ignoreCase = true) -> "#FFC800"
        merchantName.contains("zepto", ignoreCase = true) -> "#9B51E0"
        merchantName.contains("dominos", ignoreCase = true) -> "#0066B3"
        merchantName.contains("mcdonalds", ignoreCase = true) -> "#FFC600"
        merchantName.contains("kfc", ignoreCase = true) -> "#F40027"
        merchantName.contains("starbucks", ignoreCase = true) -> "#00704A"
        
        // Banks
        merchantName.contains("hdfc", ignoreCase = true) -> "#004C8F"
        merchantName.contains("icici", ignoreCase = true) -> "#F37021"
        merchantName.contains("axis", ignoreCase = true) -> "#97144D"
        merchantName.contains("sbi", ignoreCase = true) || 
        merchantName.contains("state bank of india", ignoreCase = true) -> "#22409A"
        merchantName.contains("kotak", ignoreCase = true) -> "#EF3829"
        merchantName.contains("yes bank", ignoreCase = true) -> "#0066CC"
        merchantName.contains("idfc", ignoreCase = true) -> "#8B0000"
        merchantName.contains("indusind", ignoreCase = true) -> "#98272B"
        merchantName.contains("pnb", ignoreCase = true) -> "#0E2B5C"
        merchantName.contains("prime commercial bank", ignoreCase = true) -> "#0054A6"
        merchantName.contains("mbank", ignoreCase = true) -> "#ED1C24"
        merchantName.contains("al rajhi", ignoreCase = true) -> "#0066CC"
        merchantName.contains("chase", ignoreCase = true) -> "#117ACA"
        merchantName.contains("nabil", ignoreCase = true) -> "#25A64C"
        merchantName.contains("manjushree", ignoreCase = true) -> "#EF2F1A"
        merchantName.contains("tbank", ignoreCase = true) || 
        merchantName.contains("t-bank", ignoreCase = true) ||
        merchantName.contains("tinkoff", ignoreCase = true) -> "#FFDD2D"
        merchantName.contains("everest bank", ignoreCase = true) -> "#ED1C24"
        merchantName.contains("au bank", ignoreCase = true) -> "#EC6608"
        merchantName.contains("hsbc", ignoreCase = true) -> "#DB0011"
        merchantName.contains("standard chartered", ignoreCase = true) -> "#0072AA"
        merchantName.contains("dbs", ignoreCase = true) -> "#E21A1A"
        merchantName.contains("amex", ignoreCase = true) || 
        merchantName.contains("american express", ignoreCase = true) -> "#006FCF"
        merchantName.contains("citi", ignoreCase = true) -> "#003B70"
        merchantName.contains("emirates nbd", ignoreCase = true) -> "#003366"
        merchantName.contains("mashreq", ignoreCase = true) -> "#ED1C24"
        merchantName.contains("adcb", ignoreCase = true) -> "#00263E"
        merchantName.contains("navy federal", ignoreCase = true) -> "#003468"
        merchantName.contains("huntington", ignoreCase = true) -> "#00703C"
        merchantName.contains("m-pesa", ignoreCase = true) || 
        merchantName.contains("mpesa", ignoreCase = true) -> "#4DB848"
        merchantName.contains("bancolombia", ignoreCase = true) -> "#FDDA24"
        merchantName.contains("jupiter", ignoreCase = true) -> "#F26B5B"
        merchantName.contains("equitas", ignoreCase = true) -> "#ED1C24"
        merchantName.contains("discover", ignoreCase = true) -> "#FF6000"
        merchantName.contains("schwab", ignoreCase = true) -> "#00A0DF"
        merchantName.contains("alinma", ignoreCase = true) -> "#B8964B"
        merchantName.contains("bpce", ignoreCase = true) || 
        merchantName.contains("caisse d'epargne", ignoreCase = true) -> "#642D8E"
        merchantName.contains("alecu", ignoreCase = true) -> "#003056"
        merchantName.contains("bank muscat", ignoreCase = true) -> "#003B71"
        merchantName.contains("telebirr", ignoreCase = true) -> "#E11B22"
        
        // Payments
        merchantName.contains("paytm", ignoreCase = true) -> "#00B9F1"
        merchantName.contains("phonepe", ignoreCase = true) -> "#5F259F"
        merchantName.contains("google pay", ignoreCase = true) -> "#4285F4"
        merchantName.contains("cred", ignoreCase = true) -> "#000000"
        merchantName.contains("amazon pay", ignoreCase = true) -> "#FF9900"
        
        // Telecom
        merchantName.contains("airtel", ignoreCase = true) -> "#E52E2D"
        merchantName.contains("jio", ignoreCase = true) -> "#2A3890"
        merchantName.contains("vodafone", ignoreCase = true) -> "#E60000"
        merchantName.contains("idea", ignoreCase = true) -> "#FDD922"
        merchantName.contains("bsnl", ignoreCase = true) -> "#0078BF"
        
        // Shopping
        merchantName.contains("amazon", ignoreCase = true) -> "#FF9900"
        merchantName.contains("flipkart", ignoreCase = true) -> "#027CD5"
        merchantName.contains("myntra", ignoreCase = true) -> "#FF3F6C"
        merchantName.contains("ajio", ignoreCase = true) -> "#2C4152"
        merchantName.contains("nykaa", ignoreCase = true) -> "#FC2779"
        merchantName.contains("meesho", ignoreCase = true) -> "#F43397"
        
        // Transport
        merchantName.contains("uber", ignoreCase = true) -> "#000000"
        merchantName.contains("ola", ignoreCase = true) -> "#93CE25"
        merchantName.contains("rapido", ignoreCase = true) -> "#FFC800"
        merchantName.contains("irctc", ignoreCase = true) -> "#FB792B"
        
        // Investment
        merchantName.contains("groww", ignoreCase = true) -> "#00D09C"
        merchantName.contains("zerodha", ignoreCase = true) -> "#387ED1"
        merchantName.contains("upstox", ignoreCase = true) -> "#5E72E4"
        merchantName.contains("angel", ignoreCase = true) -> "#5B2D90"
        
        // Medical
        merchantName.contains("1mg", ignoreCase = true) -> "#FC574E"
        merchantName.contains("pharmeasy", ignoreCase = true) -> "#10847E"
        merchantName.contains("netmeds", ignoreCase = true) -> "#24AEB1"
        merchantName.contains("apollo", ignoreCase = true) -> "#0066B3"
        merchantName.contains("practo", ignoreCase = true) -> "#1EBEA5"
        
        // Fitness
        merchantName.contains("cult", ignoreCase = true) -> "#FF3278"
        merchantName.contains("gym", ignoreCase = true) -> "#F15B2A"

        // Additional brands
        merchantName.contains("airbnb", ignoreCase = true) -> "#FF5A5F"
        merchantName.contains("apple tv", ignoreCase = true) -> "#000000"
        merchantName.contains("bumble", ignoreCase = true) -> "#FFC000"
        merchantName.contains("chatgpt", ignoreCase = true) -> "#74AA9C"
        merchantName.contains("claude", ignoreCase = true) -> "#D97757"
        merchantName.contains("crunchyroll", ignoreCase = true) -> "#F47521"
        merchantName.contains("disney plus", ignoreCase = true) -> "#113CCF"
        merchantName.contains("fastag", ignoreCase = true) -> "#F79620"
        merchantName.contains("gemini", ignoreCase = true) -> "#1A73E8"
        merchantName.contains("grok", ignoreCase = true) -> "#000000"
        merchantName.contains("hbo max", ignoreCase = true) -> "#5822B4"
        merchantName.contains("jiocinema", ignoreCase = true) -> "#E50914"
        merchantName.contains("jiohotstar", ignoreCase = true) -> "#E50914"
        merchantName.contains("oyo", ignoreCase = true) -> "#2C3E50"
        merchantName.contains("perplexity", ignoreCase = true) -> "#1E3A5F"
        merchantName.contains("playstation", ignoreCase = true) -> "#003791"
        merchantName.contains("proton vpn", ignoreCase = true) -> "#6D4AFF"
        merchantName.contains("visa", ignoreCase = true) -> "#1A1F71"
        merchantName.contains("xbox", ignoreCase = true) -> "#107C10"
        merchantName.contains("youtube music", ignoreCase = true) -> "#FF0000"

        else -> null
    }
}
