import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { SchemeTonalSpot, Hct, argbFromHex, hexFromArgb } from '@material/material-color-utilities';

// Official MCU generation, explicitly pinned to the standard MD3 tonal-spot spec.
// Run `npm ci && npm run generate` in this directory. No Android runtime dependency.
const seeds = JSON.parse(readFileSync(new URL('./seeds.json', import.meta.url)));
const roles = ['primary', 'onPrimary', 'primaryContainer', 'onPrimaryContainer', 'inversePrimary',
    'secondary', 'onSecondary', 'secondaryContainer', 'onSecondaryContainer',
    'tertiary', 'onTertiary', 'tertiaryContainer', 'onTertiaryContainer',
    'background', 'onBackground', 'surface', 'onSurface', 'surfaceVariant', 'onSurfaceVariant',
    'surfaceTint', 'inverseSurface', 'inverseOnSurface', 'error', 'onError', 'errorContainer', 'onErrorContainer',
    'outline', 'outlineVariant', 'scrim', 'surfaceBright', 'surfaceDim', 'surfaceContainer',
    'surfaceContainerHigh', 'surfaceContainerHighest', 'surfaceContainerLow', 'surfaceContainerLowest',
    'primaryFixed', 'primaryFixedDim', 'onPrimaryFixed', 'onPrimaryFixedVariant',
    'secondaryFixed', 'secondaryFixedDim', 'onSecondaryFixed', 'onSecondaryFixedVariant',
    'tertiaryFixed', 'tertiaryFixedDim', 'onTertiaryFixed', 'onTertiaryFixedVariant'];
const aliases = { inverseOnSurface: 'inverseOnSurface' };
const all = Object.fromEntries(Object.entries(seeds).map(([name, seed]) => [name,
    [false, true].map(dark => {
        const scheme = new SchemeTonalSpot(Hct.fromInt(argbFromHex(seed)), dark, 0, '2021', 'phone');
        return Object.fromEntries(roles.map(role => {
            const value = scheme[aliases[role] ?? role];
            if (!Number.isFinite(value)) throw new Error(`Missing role ${role}`);
            return [role, hexFromArgb(value)];
        }));
    })
]));
const arrays = Object.entries(all).map(([name, modes]) => `        AccentColor.${name} -> if (dark) longArrayOf(\n${format(modes[1])}\n        ) else longArrayOf(\n${format(modes[0])}\n        )`).join('\n');
function format(mode) { return roles.map(role => `            0xFF${mode[role].slice(1).toUpperCase()}, // ${role}`).join('\n'); }
const parameters = roles.map((role, i) => `        ${role} = Color(colors[${i}]),`).join('\n');
const code = `// Generated by scripts/md3/generate.mjs; edit seeds.json, not this file.
// Google Material Color Utilities 0.4.0 · SchemeTonalSpot · spec 2021 · contrast 0.0.
// https://github.com/material-foundation/material-color-utilities
package com.ritesh.cashiro.presentation.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.ui.graphics.Color
import com.ritesh.cashiro.data.preferences.AccentColor
import java.util.concurrent.ConcurrentHashMap

private val lightTonalSchemes = ConcurrentHashMap<AccentColor, ColorScheme>()
private val darkTonalSchemes = ConcurrentHashMap<AccentColor, ColorScheme>()

fun getCustomLightColorScheme(accent: AccentColor): ColorScheme =
    lightTonalSchemes.getOrPut(accent) { createTonalScheme(accent, false) }

fun getCustomDarkColorScheme(accent: AccentColor): ColorScheme =
    darkTonalSchemes.getOrPut(accent) { createTonalScheme(accent, true) }

private fun createTonalScheme(accent: AccentColor, dark: Boolean): ColorScheme {
    val colors = when (accent) {
${arrays}
    }
    return if (dark) darkColorScheme(
${parameters}
    ) else lightColorScheme(
${parameters}
    )
}
`;
const output = new URL('../../app/src/main/java/com/ritesh/cashiro/presentation/ui/theme/TonalColorSchemes.kt', import.meta.url);
writeFileSync(output, code);
writeFileSync(new URL('./palettes.json', import.meta.url), JSON.stringify({ generator: '@material/material-color-utilities@0.4.0', variant: 'SchemeTonalSpot', spec: '2021', contrast: 0, seeds, palettes: all }, null, 2) + '\n');
console.log(`Generated ${Object.keys(seeds).length * 2} light/dark schemes with ${roles.length} independent MD3 roles.`);
console.log('GREEN light:', JSON.stringify(all.GREEN[0]));
console.log('Output:', fileURLToPath(output));
